version: 4.0.0.{build}

configuration: Release

branches:
  only:
  - master

build_script:
- build.cmd

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: N4KZCRegcmenMoJ0peZfQwDzqq+Wt4oxGzNTgvkrDxgWyZhw7hNwKmd4n2AsNKQX
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac